channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - ipython
  - nbsphinx
  - numpydoc
  - sphinx
  - sphinx-autoapi
  - sphinxcontrib-bibtex
  - pydata-sphinx-theme>=0.3.0
  - parso>=0.8.1
