channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - ipython
  - nbsphinx
  - numpydoc
  - sphinx
  - sphinx-autoapi<1.7.0
  - sphinxcontrib-bibtex<2.0.0
  - pydata-sphinx-theme>=0.3.0
  - parso>=0.8.1
